// app.config.js
import 'dotenv/config';

export default {
 expo: {
    owner: "your-zeros-and-ones",
    name: "Cureli",
    slug: "cureli-mobile",
    version: "1.0.0",
    orientation: "portrait",
    icon: "./assets/images/icon.png",
    scheme: "curelimobile",
    userInterfaceStyle: "automatic",
    newArchEnabled: true,
    ios: {
      supportsTablet: true,
      bundleIdentifier: "com.cureli.mobile",
      infoPlist: {
        NSLocationWhenInUseUsageDescription:
          "Cureli needs your location to help fill your delivery address.",
        NSLocationAlwaysAndWhenInUseUsageDescription:
          "Cureli needs your location to help fill your delivery address.",
      },
      config: {
        googleMapsApiKey: process.env.EXPO_PUBLIC_GOOGLE_MAPS_KEY,
      },
    },
    android: {
      adaptiveIcon: {
        backgroundColor: "#090025",
        foregroundImage: "./assets/images/android-icon-foreground.png",
        monochromeImage: "./assets/images/android-icon-monochrome.png",
      },
      edgeToEdgeEnabled: true,
      predictiveBackGestureEnabled: false,
      package: "com.cureli.mobile",
      // ── FCM / Google Services ─────────────────────────────────────────────
      googleServicesFile: "./google-services.json",
      // ── Push notification permissions ─────────────────────────────────────
      permissions: [
        "android.permission.POST_NOTIFICATIONS",
        "android.permission.RECEIVE_BOOT_COMPLETED",
        "android.permission.VIBRATE",
      ],
      // ── Maps ──────────────────────────────────────────────────────────────
      config: {
        googleMaps: {
          apiKey: process.env.EXPO_PUBLIC_GOOGLE_MAPS_KEY,
        },
      },
    },
    web: {
      output: "static",
      favicon: "./assets/images/favicon.png",
    },
    plugins: [
      "expo-dev-client",
      "expo-router",
      [
        "expo-splash-screen",
        {
          image: "./assets/images/cureliwhitenew.png",
          imageWidth: 160,
          resizeMode: "contain",
          backgroundColor: "#05015A",
        },
      ],
      "expo-font",
      [
        "expo-location",
        {
          locationWhenInUsePermission:
            "Cureli needs your location to help fill your delivery address.",
          isIosBackgroundLocationEnabled: false,
          isAndroidBackgroundLocationEnabled: false,
        },
      ],
      // ── expo-notifications ────────────────────────────────────────────────
      [
        "expo-notifications",
        {
          icon: "./assets/images/android-icon-monochrome.png",
          color: "#05015A",
          defaultChannel: "default",
          sounds: [],
        },
      ],
    ],
    experiments: {
      typedRoutes: true,
      reactCompiler: true,
    },
    // ── EAS / Expo Project ID ─────────────────────────────────────────────
    // Required for Expo push tokens (SDK 50+).
    // Generated by: npx eas init
    // Dashboard: https://expo.dev/accounts/yourzerosandones/projects/cureli-mobile
    extra: {
      router: {},
      eas: {
         projectId: "ad36bf8e-0d58-4e84-acc9-7e64b7b4cdee",
      },
    },
  },
};