// src/features/marketplace/hooks/useMedicineDetail.ts
//
// Fetches a single variant (+ siblings) for the product detail screen.
// Accepts a skuId or variant UUID — the service handles dual lookup.
//
// PHASE 5 CHANGE:
//   variant is now typed as EnrichedMedicineDetail | null instead of
//   EnrichedMedicine | null. EnrichedMedicineDetail has:
//     - marketer, description, images (full gallery) from MedicineVariantDetail
//     - availableNearYou: boolean (non-optional) — always present on the
//       detail response, enforced at the type level so the detail screen
//       never needs to null-check it
//
//   The enrichment spread is unchanged — generateMarketplaceData still
//   produces the fake marketplace decoration from the variantId seed.
//   availableNearYou comes from the backend and passes through the spread
//   unchanged. In demo mode it is always true. In production mode it
//   reflects real listing visibility.
//
// Siblings remain EnrichedMedicine[] — they are feed-level items
// and do not carry availableNearYou.

import { useQuery } from "@tanstack/react-query";
import { marketplaceApi } from "../api/marketplace.api";
import { generateMarketplaceData } from "../utils/generateMarketplaceData";
import type {
  EnrichedMedicine,
  EnrichedMedicineDetail,
  MedicineVariant,
} from "../types/marketplace.types";

export function medicineDetailKey(idOrSku: string) {
  return ["medicines", "detail", idOrSku] as const;
}

export function useMedicineDetail(idOrSku: string) {
  const query = useQuery({
    queryKey: medicineDetailKey(idOrSku),
    queryFn: () => marketplaceApi.getMedicine(idOrSku),
    enabled: !!idOrSku,
    staleTime: 1000 * 60 * 5, // 5 min — matches root QueryClient default
  });

  // Enrich the main variant with fake marketplace data.
  // availableNearYou arrives from the backend as part of the spread —
  // it is not generated by generateMarketplaceData.
  const variant: EnrichedMedicineDetail | null = query.data?.variant
    ? {
        ...query.data.variant,
        marketplace: generateMarketplaceData(query.data.variant.variantId),
      }
    : null;

  // Siblings are enriched for consistent price/ETA display on the
  // sibling rail. They do not carry availableNearYou.
  const siblings: EnrichedMedicine[] =
    query.data?.siblings.map((s: MedicineVariant) => ({
      ...s,
      marketplace: generateMarketplaceData(s.variantId),
    })) ?? [];

  return {
    variant,
    siblings,
    isLoading: query.isLoading,
    isError: query.isError,
    error: query.error,
    refetch: query.refetch,
  };
}