// cadmin/src/pages/MasterMedicines/mockMasterMedicineData.js

/**
 * ══════════════════════════════════════════════════════════════
 * MOCK DATA FOR MASTER MEDICINES V2
 * ══════════════════════════════════════════════════════════════
 */

// ═══════════════════════════════════════════════════════════════
// MAPPED MEDICINES (Clean master catalog)
// ═══════════════════════════════════════════════════════════════
export const MOCK_MAPPED_MEDICINES = [
  {
    id: "mm-001",
    name: "Paracetamol 500mg Tablet",
    normalizedName: "paracetamol 500mg tablet",
    composition: "Paracetamol (500mg)",
    type: "DRUG",
    manufacturer: "Cipla Ltd",
    marketer: "Cipla Ltd",
    packSize: "10 tablets in 1 strip",
    prescriptionRequired: false,
    isActive: true,
    hasImage: true,
    primaryImage: "DRUGS_IMAGES/mock_paracetamol/phase1_main.jpg",
    createdAt: "2024-03-15T10:30:00Z",
    updatedAt: "2024-03-15T10:30:00Z",
  },
  {
    id: "mm-002",
    name: "Amoxicillin 500mg Capsule",
    normalizedName: "amoxicillin 500mg capsule",
    composition: "Amoxicillin (500mg)",
    type: "DRUG",
    manufacturer: "Sun Pharma",
    marketer: "Sun Pharmaceutical Industries",
    packSize: "15 capsules in 1 strip",
    prescriptionRequired: true,
    isActive: true,
    hasImage: true,
    primaryImage: "DRUGS_IMAGES/mock_amoxicillin/phase1_main.jpg",
    createdAt: "2024-03-14T09:00:00Z",
    updatedAt: "2024-03-14T09:00:00Z",
  },
  {
    id: "mm-003",
    name: "Cetirizine 10mg Tablet",
    normalizedName: "cetirizine 10mg tablet",
    composition: "Cetirizine (10mg)",
    type: "OTC",
    manufacturer: "Dr. Reddy's",
    marketer: "Dr. Reddy's Laboratories",
    packSize: "10 tablets in 1 strip",
    prescriptionRequired: false,
    isActive: true,
    hasImage: false, // No image
    primaryImage: null,
    createdAt: "2024-03-13T14:20:00Z",
    updatedAt: "2024-03-13T14:20:00Z",
  },
  {
    id: "mm-004",
    name: "Omeprazole 20mg Capsule",
    normalizedName: "omeprazole 20mg capsule",
    composition: "Omeprazole (20mg)",
    type: "DRUG",
    manufacturer: "Mankind Pharma",
    marketer: "Mankind Pharma Ltd",
    packSize: "15 capsules in 1 strip",
    prescriptionRequired: true,
    isActive: true,
    hasImage: true,
    primaryImage: "DRUGS_IMAGES/mock_omeprazole/phase1_main.jpg",
    createdAt: "2024-03-12T11:45:00Z",
    updatedAt: "2024-03-12T11:45:00Z",
  },
  {
    id: "mm-005",
    name: "Vitamin D3 60000 IU Capsule",
    normalizedName: "vitamin d3 60000 iu capsule",
    composition: "Cholecalciferol (60000 IU)",
    type: "OTC",
    manufacturer: "Abbott Healthcare",
    marketer: "Abbott India Ltd",
    packSize: "4 capsules in 1 strip",
    prescriptionRequired: false,
    isActive: true,
    hasImage: true,
    primaryImage: "OTC_IMAGES/mock_vitamind3/phase1_main.jpg",
    createdAt: "2024-03-11T16:30:00Z",
    updatedAt: "2024-03-11T16:30:00Z",
  },
  {
    id: "mm-006",
    name: "Metformin 500mg Tablet",
    normalizedName: "metformin 500mg tablet",
    composition: "Metformin Hydrochloride (500mg)",
    type: "DRUG",
    manufacturer: "USV Pvt Ltd",
    marketer: "USV Private Limited",
    packSize: "20 tablets in 1 strip",
    prescriptionRequired: true,
    isActive: true,
    hasImage: false, // No image
    primaryImage: null,
    createdAt: "2024-03-10T08:15:00Z",
    updatedAt: "2024-03-10T08:15:00Z",
  },
  {
    id: "mm-007",
    name: "Azithromycin 500mg Tablet",
    normalizedName: "azithromycin 500mg tablet",
    composition: "Azithromycin (500mg)",
    type: "DRUG",
    manufacturer: "Alkem Laboratories",
    marketer: "Alkem Laboratories Ltd",
    packSize: "3 tablets in 1 strip",
    prescriptionRequired: true,
    isActive: true,
    hasImage: true,
    primaryImage: "DRUGS_IMAGES/mock_azithromycin/phase1_main.jpg",
    createdAt: "2024-03-09T13:00:00Z",
    updatedAt: "2024-03-09T13:00:00Z",
  },
  {
    id: "mm-008",
    name: "Calcium + Vitamin D3 Tablet",
    normalizedName: "calcium vitamin d3 tablet",
    composition: "Calcium Carbonate (500mg) + Vitamin D3 (250 IU)",
    type: "OTC",
    manufacturer: "Pfizer Ltd",
    marketer: "Pfizer Limited",
    packSize: "15 tablets in 1 strip",
    prescriptionRequired: false,
    isActive: true,
    hasImage: true,
    primaryImage: "OTC_IMAGES/mock_calcium/phase1_main.jpg",
    createdAt: "2024-03-08T10:00:00Z",
    updatedAt: "2024-03-08T10:00:00Z",
  },
  {
    id: "mm-009",
    name: "Pantoprazole 40mg Tablet",
    normalizedName: "pantoprazole 40mg tablet",
    composition: "Pantoprazole (40mg)",
    type: "DRUG",
    manufacturer: "Torrent Pharmaceuticals",
    marketer: "Torrent Pharma",
    packSize: "15 tablets in 1 strip",
    prescriptionRequired: true,
    isActive: true,
    hasImage: false, // No image
    primaryImage: null,
    createdAt: "2024-03-07T15:30:00Z",
    updatedAt: "2024-03-07T15:30:00Z",
  },
  {
    id: "mm-010",
    name: "Ibuprofen 400mg Tablet",
    normalizedName: "ibuprofen 400mg tablet",
    composition: "Ibuprofen (400mg)",
    type: "OTC",
    manufacturer: "GlaxoSmithKline",
    marketer: "GSK Consumer Healthcare",
    packSize: "10 tablets in 1 strip",
    prescriptionRequired: false,
    isActive: true,
    hasImage: true,
    primaryImage: "OTC_IMAGES/mock_ibuprofen/phase1_main.jpg",
    createdAt: "2024-03-06T09:45:00Z",
    updatedAt: "2024-03-06T09:45:00Z",
  },
  {
    id: "mm-011",
    name: "Dolo 650 Tablet",
    normalizedName: "dolo 650 tablet",
    composition: "Paracetamol (650mg)",
    type: "OTC",
    manufacturer: "Micro Labs",
    marketer: "Micro Labs Limited",
    packSize: "15 tablets in 1 strip",
    prescriptionRequired: false,
    isActive: true,
    hasImage: true,
    primaryImage: "OTC_IMAGES/mock_dolo/phase1_main.jpg",
    createdAt: "2024-03-05T12:20:00Z",
    updatedAt: "2024-03-05T12:20:00Z",
  },
  {
    id: "mm-012",
    name: "Crocin Advance 500mg Tablet",
    normalizedName: "crocin advance 500mg tablet",
    composition: "Paracetamol (500mg)",
    type: "OTC",
    manufacturer: "GlaxoSmithKline",
    marketer: "GSK Consumer Healthcare",
    packSize: "15 tablets in 1 strip",
    prescriptionRequired: false,
    isActive: true,
    hasImage: false,
    primaryImage: null,
    createdAt: "2024-03-04T08:00:00Z",
    updatedAt: "2024-03-04T08:00:00Z",
  },
];

// ═══════════════════════════════════════════════════════════════
// UNMAPPED MEDICINES (Grouped by normalized name)
// ═══════════════════════════════════════════════════════════════
export const MOCK_UNMAPPED_MEDICINES = [
  {
    id: "um-001",
    normalizedName: "pcm 500",
    sampleNames: [
      "PCM 500 TAB",
      "PCM500",
      "Paracetamol 500",
      "PCM-500 Tablet",
      "P.C.M. 500mg",
    ],
    occurrenceCount: 47,
    shopCount: 12,
    type: "DRUG",
    hasImageSuggestion: true,
    firstSeenAt: "2024-03-01T10:00:00Z",
    lastSeenAt: "2024-03-18T14:30:00Z",
    shops: [
      { id: "shop-1", name: "City Pharmacy", count: 8 },
      { id: "shop-2", name: "MedPlus", count: 12 },
      { id: "shop-3", name: "Apollo Pharmacy", count: 6 },
      { id: "shop-4", name: "Wellness Pharma", count: 5 },
      { id: "shop-5", name: "LifeCare Medical", count: 16 },
    ],
  },
  {
    id: "um-002",
    normalizedName: "amox 500",
    sampleNames: [
      "AMOX 500 CAP",
      "Amox-500",
      "Amoxycillin 500mg",
    ],
    occurrenceCount: 23,
    shopCount: 5,
    type: "DRUG",
    hasImageSuggestion: false,
    firstSeenAt: "2024-03-05T09:00:00Z",
    lastSeenAt: "2024-03-17T11:20:00Z",
    shops: [
      { id: "shop-1", name: "City Pharmacy", count: 5 },
      { id: "shop-6", name: "Health First", count: 8 },
      { id: "shop-7", name: "Care Chemist", count: 10 },
    ],
  },
  {
    id: "um-003",
    normalizedName: "cetzine 10",
    sampleNames: [
      "Cetzine 10mg",
      "CETZINE-10",
      "Cetzine Tab",
      "Cetzine 10 Tablet",
    ],
    occurrenceCount: 34,
    shopCount: 8,
    type: "OTC",
    hasImageSuggestion: true,
    firstSeenAt: "2024-03-02T14:00:00Z",
    lastSeenAt: "2024-03-18T16:45:00Z",
    shops: [
      { id: "shop-2", name: "MedPlus", count: 15 },
      { id: "shop-3", name: "Apollo Pharmacy", count: 10 },
      { id: "shop-8", name: "Netmeds Store", count: 9 },
    ],
  },
  {
    id: "um-004",
    normalizedName: "pan 40",
    sampleNames: [
      "PAN 40",
      "Pan-40 Tab",
      "Pantop 40",
      "Pan D 40",
      "Pantocid 40mg",
      "Pan 40mg Tablet",
    ],
    occurrenceCount: 56,
    shopCount: 15,
    type: "DRUG",
    hasImageSuggestion: false,
    firstSeenAt: "2024-02-28T08:00:00Z",
    lastSeenAt: "2024-03-18T18:00:00Z",
    shops: [
      { id: "shop-1", name: "City Pharmacy", count: 12 },
      { id: "shop-2", name: "MedPlus", count: 18 },
      { id: "shop-3", name: "Apollo Pharmacy", count: 8 },
      { id: "shop-4", name: "Wellness Pharma", count: 18 },
    ],
  },
  {
    id: "um-005",
    normalizedName: "vitamin d3 sachet",
    sampleNames: [
      "Vit D3 Sachet",
      "Vitamin D3 60K",
      "D3 Sachet 60000",
    ],
    occurrenceCount: 18,
    shopCount: 4,
    type: "OTC",
    hasImageSuggestion: true,
    firstSeenAt: "2024-03-08T11:00:00Z",
    lastSeenAt: "2024-03-16T09:30:00Z",
    shops: [
      { id: "shop-5", name: "LifeCare Medical", count: 8 },
      { id: "shop-9", name: "PharmEasy Store", count: 10 },
    ],
  },
  {
    id: "um-006",
    normalizedName: "azee 500",
    sampleNames: [
      "AZEE 500",
      "Azee-500 Tab",
      "Azithral 500",
      "Azithromycin 500mg Tab",
    ],
    occurrenceCount: 29,
    shopCount: 7,
    type: "DRUG",
    hasImageSuggestion: true,
    firstSeenAt: "2024-03-04T10:00:00Z",
    lastSeenAt: "2024-03-17T15:00:00Z",
    shops: [
      { id: "shop-1", name: "City Pharmacy", count: 6 },
      { id: "shop-6", name: "Health First", count: 12 },
      { id: "shop-10", name: "Medkart", count: 11 },
    ],
  },
  {
    id: "um-007",
    normalizedName: "combiflam",
    sampleNames: [
      "Combiflam Tab",
      "COMBIFLAM",
      "Combiflam Tablet",
    ],
    occurrenceCount: 41,
    shopCount: 11,
    type: "OTC",
    hasImageSuggestion: false,
    firstSeenAt: "2024-03-01T08:30:00Z",
    lastSeenAt: "2024-03-18T12:00:00Z",
    shops: [
      { id: "shop-2", name: "MedPlus", count: 20 },
      { id: "shop-3", name: "Apollo Pharmacy", count: 21 },
    ],
  },
  {
    id: "um-008",
    normalizedName: "metformin sr 500",
    sampleNames: [
      "Metformin SR 500",
      "MET SR 500",
      "Glycomet SR 500",
      "Metformin 500 SR Tab",
      "Met-SR 500mg",
    ],
    occurrenceCount: 38,
    shopCount: 9,
    type: "DRUG",
    hasImageSuggestion: true,
    firstSeenAt: "2024-02-25T07:00:00Z",
    lastSeenAt: "2024-03-18T10:15:00Z",
    shops: [
      { id: "shop-4", name: "Wellness Pharma", count: 15 },
      { id: "shop-7", name: "Care Chemist", count: 13 },
      { id: "shop-11", name: "Diabetes Care Center", count: 10 },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════
// NEEDS REVIEW (Auto-suggested matches with confidence scores)
// ═══════════════════════════════════════════════════════════════
export const MOCK_NEEDS_REVIEW = [
  {
    id: "nr-001",
    rawName: "Calpol 500",
    normalizedRaw: "calpol 500",
    suggestedMaster: {
      id: "mm-001",
      name: "Paracetamol 500mg Tablet",
      manufacturer: "Cipla Ltd",
      type: "DRUG",
      hasImage: true,
    },
    confidenceScore: 78,
    confidenceReason: "Similar composition detected",
    shopId: "shop-1",
    shopName: "City Pharmacy",
    occurrenceCount: 5,
    firstSeenAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "nr-002",
    rawName: "Mox 500 Cap",
    normalizedRaw: "mox 500 cap",
    suggestedMaster: {
      id: "mm-002",
      name: "Amoxicillin 500mg Capsule",
      manufacturer: "Sun Pharma",
      type: "DRUG",
      hasImage: true,
    },
    confidenceScore: 85,
    confidenceReason: "Name pattern match + same strength",
    shopId: "shop-2",
    shopName: "MedPlus",
    occurrenceCount: 8,
    firstSeenAt: "2024-03-14T09:30:00Z",
  },
  {
    id: "nr-003",
    rawName: "Rantac 150",
    normalizedRaw: "rantac 150",
    suggestedMaster: {
      id: "mm-004",
      name: "Omeprazole 20mg Capsule",
      manufacturer: "Mankind Pharma",
      type: "DRUG",
      hasImage: true,
    },
    confidenceScore: 45,
    confidenceReason: "Same therapeutic class (antacid)",
    shopId: "shop-3",
    shopName: "Apollo Pharmacy",
    occurrenceCount: 3,
    firstSeenAt: "2024-03-16T11:00:00Z",
  },
  {
    id: "nr-004",
    rawName: "Cetrizine Tab",
    normalizedRaw: "cetrizine tab",
    suggestedMaster: {
      id: "mm-003",
      name: "Cetirizine 10mg Tablet",
      manufacturer: "Dr. Reddy's",
      type: "OTC",
      hasImage: false,
    },
    confidenceScore: 92,
    confidenceReason: "Exact composition match",
    shopId: "shop-4",
    shopName: "Wellness Pharma",
    occurrenceCount: 12,
    firstSeenAt: "2024-03-13T14:30:00Z",
  },
  {
    id: "nr-005",
    rawName: "D3 Must Sachet",
    normalizedRaw: "d3 must sachet",
    suggestedMaster: {
      id: "mm-005",
      name: "Vitamin D3 60000 IU Capsule",
      manufacturer: "Abbott Healthcare",
      type: "OTC",
      hasImage: true,
    },
    confidenceScore: 68,
    confidenceReason: "Same vitamin type, different form",
    shopId: "shop-5",
    shopName: "LifeCare Medical",
    occurrenceCount: 6,
    firstSeenAt: "2024-03-12T16:00:00Z",
  },
  {
    id: "nr-006",
    rawName: "Glycomet 500",
    normalizedRaw: "glycomet 500",
    suggestedMaster: {
      id: "mm-006",
      name: "Metformin 500mg Tablet",
      manufacturer: "USV Pvt Ltd",
      type: "DRUG",
      hasImage: false,
    },
    confidenceScore: 95,
    confidenceReason: "Brand name of same salt",
    shopId: "shop-6",
    shopName: "Health First",
    occurrenceCount: 15,
    firstSeenAt: "2024-03-10T08:45:00Z",
  },
  {
    id: "nr-007",
    rawName: "Azithral 250",
    normalizedRaw: "azithral 250",
    suggestedMaster: {
      id: "mm-007",
      name: "Azithromycin 500mg Tablet",
      manufacturer: "Alkem Laboratories",
      type: "DRUG",
      hasImage: true,
    },
    confidenceScore: 58,
    confidenceReason: "Same salt, different strength",
    shopId: "shop-7",
    shopName: "Care Chemist",
    occurrenceCount: 4,
    firstSeenAt: "2024-03-09T13:20:00Z",
  },
  {
    id: "nr-008",
    rawName: "Shelcal 500",
    normalizedRaw: "shelcal 500",
    suggestedMaster: {
      id: "mm-008",
      name: "Calcium + Vitamin D3 Tablet",
      manufacturer: "Pfizer Ltd",
      type: "OTC",
      hasImage: true,
    },
    confidenceScore: 82,
    confidenceReason: "Same category and strength",
    shopId: "shop-8",
    shopName: "Netmeds Store",
    occurrenceCount: 9,
    firstSeenAt: "2024-03-08T10:30:00Z",
  },
];

// ═══════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════

/**
 * Get confidence level styling
 */
export function getConfidenceLevel(score) {
  if (score >= 90) return { level: "high", color: "green", label: "High" };
  if (score >= 70) return { level: "medium", color: "yellow", label: "Medium" };
  if (score >= 50) return { level: "low", color: "orange", label: "Low" };
  return { level: "very-low", color: "red", label: "Very Low" };
}

/**
 * Get confidence bar color classes
 */
export function getConfidenceColorClasses(score) {
  if (score >= 90) return { bg: "bg-green-500", text: "text-green-700", badge: "bg-green-100 text-green-800" };
  if (score >= 70) return { bg: "bg-yellow-500", text: "text-yellow-700", badge: "bg-yellow-100 text-yellow-800" };
  if (score >= 50) return { bg: "bg-orange-500", text: "text-orange-700", badge: "bg-orange-100 text-orange-800" };
  return { bg: "bg-red-500", text: "text-red-700", badge: "bg-red-100 text-red-800" };
}